services:

  db:
    restart: always
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tiger
      - POSTGRES_USER=scott
      - POSTGRES_DB=demodb

volumes:
  db:
    driver:
      local
