services:

  db:
    restart: always
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tiger
      - POSTGRES_USER=scott
      - POSTGRES_DB=demodb

  app:
    restart: always
    image: ghcr.io/rmortale/postgres-microservice-ec2:master
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demodb
